solution
mate-academy/layout_miami pull request #1011
Opened 2022-04-14 18:40 UTC by yelnikov-andrii

2022-04-15 08:04 UTC, Denchepornyuk commented
<img width="1440" alt="Screenshot 2022-04-15 at 11 00 03" src="https://user-images.githubusercontent.com/37452763/163543092-a9d0d836-8b03-4bfe-97de-e5b7ef992972.png">

something is wrong with the image, fix the image size

2022-04-15 08:06 UTC, Denchepornyuk commented
<img width="235" alt="Screenshot 2022-04-15 at 11 05 49" src="https://user-images.githubusercontent.com/37452763/163543791-17c09a84-8895-4010-be35-4735db9766fb.png">

fix the text in browser tab

2022-04-15 08:07 UTC, Denchepornyuk commented
<img width="1067" alt="Screenshot 2022-04-15 at 11 06 26" src="https://user-images.githubusercontent.com/37452763/163543863-00f0799e-f6f6-4469-b93d-8e0465bd2afe.png">

fix images, check images in the design

2022-04-15 08:08 UTC, Denchepornyuk commented
<img width="526" alt="Screenshot 2022-04-15 at 11 07 38" src="https://user-images.githubusercontent.com/37452763/163543976-34506588-6891-4046-b0eb-a49812b43649.png">

fix images width on small screen, check images in the design

2022-04-15 08:09 UTC, Denchepornyuk requested changes
good job

2022-04-15 08:09 UTC, Denchepornyuk commented on src/index.html
> +              >
fix intends in all places
```suggestion
              <img
                src="./images/logo.svg"
                alt="bose"
                class="logo__img"
              >
```

2022-04-15 14:22 UTC, Denchepornyuk commented
<img width="1077" alt="Screenshot 2022-04-15 at 17 22 40" src="https://user-images.githubusercontent.com/37452763/163582351-66feb461-8bf1-4912-84e4-f80386d8fdab.png">

add a small hover effect for images
a small scale would be great

2022-04-15 14:27 UTC, Denchepornyuk commented
<img width="834" alt="Screenshot 2022-04-15 at 17 25 46" src="https://user-images.githubusercontent.com/37452763/163582672-4156d615-d38b-472d-b459-64a4dfba2cac.png">

дуже рано робиш мобільну версію для сторінки, зробити сайт більшим на ширині між 480 і 768 px, а від 480 вже залишай мобільну версію

2022-04-18 11:09 UTC, Anna-Tkachenko approved these changes
Good job! 👍 
Some comments:
1) Don't forget to add favicon to your page
2) Logo in header should be the link (you can add # in href for it)
3) Will be better to set height of header = 100vh, now I don't see full title text
<img width="1439" alt="image" src="https://user-images.githubusercontent.com/30314756/163799920-decc79d1-054e-48e5-8ec9-a2a044e2f849.png">
4) Add some styles on hover state for images in 'recommended' section
5) Add some styles on hover state for links near contact form
6) Address link near the contact form should be opened in the new tab

2024-03-19 14:48 UTC, closed without merging