miami page
mate-academy/layout_miami pull request #1088
Opened 2022-05-25 11:36 UTC by leonid-levtseniuk

2022-05-26 17:51 UTC, vkryvytskyy requested changes

2022-05-26 17:51 UTC, vkryvytskyy commented on src/index.html
> +<html lang="en" class="page">
https://user-images.githubusercontent.com/38065883/170545988-6a90cb3b-03d5-42fc-b622-3edcdd783caf.mov

Форма отправляется пустой, сделай поля required

2022-05-26 17:51 UTC, vkryvytskyy commented on src/index.html
> +<html lang="en" class="page">
![image](https://user-images.githubusercontent.com/38065883/170546150-058bf0c1-1e21-4572-aa21-84d0c76775ca.png)
При открытом меню картинки налезают на него

2022-05-26 17:51 UTC, vkryvytskyy commented on src/index.html
> +<html lang="en" class="page">
![image](https://user-images.githubusercontent.com/38065883/170546244-6e3c1293-b29f-4cc4-974d-b3a7caa9758a.png)
На 1023 слишком большие картинки

2022-05-27 12:57 UTC, leonid-levtseniuk commented
Звідкись взявся комміт "make build" я його не створював і не пушив, зараз не виходить задеплоїти сторінку

2022-05-28 14:49 UTC, leonid-levtseniuk commented
Ментор допоміг, все працює

2022-05-28 15:20 UTC, vkryvytskyy approved these changes

2022-05-28 15:22 UTC, closed without merging