Develop
mate-academy/layout_miami pull request #1118
Opened 2022-05-27 07:51 UTC by juajum

- [DEMO LINK](https://juajum.github.io/layout_miami/)

2022-05-27 11:56 UTC, illiarerun requested changes
Nice start, now let's work on fixes:

2022-05-27 11:56 UTC, illiarerun commented on src/index.html
>    </head>
Checklist 1st item

2022-05-27 11:56 UTC, illiarerun commented on src/index.html
> +    <header class="page__section header">
Header should stretch for the whole viewport height
![image](https://user-images.githubusercontent.com/37161315/170693849-6b740529-5771-4edf-b739-faacdb65a1cd.png)

2022-05-27 11:56 UTC, illiarerun commented on src/index.html
> +            <a href="/" class="logo">
Checklsit 5th and 6th items

2022-05-27 11:56 UTC, illiarerun commented on src/index.html
> +              </a>
Checklist 5th item
![image](https://user-images.githubusercontent.com/37161315/170693976-485f6c79-aebe-4d10-a3eb-15e0be8798db.png)

2022-05-27 11:56 UTC, illiarerun commented on src/index.html
> +    <nav class="page__menu menu" id="menu">
It's weird that I click on menu on the right side of the page and it comes out from the left side

2022-05-27 11:56 UTC, illiarerun commented on src/index.html
> +            </li>
These all should to some sections on the page, add corresponding ids

2022-05-27 11:56 UTC, illiarerun commented on src/index.html
> +                </a>
Checklist 9th item

2022-05-27 11:56 UTC, illiarerun commented on src/index.html
> +                <a href="email:hello@miami.com" class="contact-us__info-link">
`email:` does nothing, `mailto:` is a way to go

2022-05-27 11:56 UTC, illiarerun commented on src/index.html
> +            <div class="contact-us__info-container">
Add some hover effects here
![image](https://user-images.githubusercontent.com/37161315/170694563-5079621d-d367-48ec-bc61-70641bc3e4e0.png)

2022-05-27 11:56 UTC, illiarerun commented on src/index.html
> +              ></textarea>
Checklist 14th item

2022-05-27 11:56 UTC, illiarerun commented on src/index.html
> +              <a href="button" class="button">Send</a>
That's what I see when I click on this button
![image](https://user-images.githubusercontent.com/37161315/170694661-a71d5808-0de0-4202-b447-6030a8e2d71e.png)

2022-05-27 11:56 UTC, illiarerun commented on src/index.html
> +    <nav class="page__menu menu" id="menu">
Checklist 18th item
![image](https://user-images.githubusercontent.com/37161315/170694785-e7189025-f169-489c-a12b-18450d83d799.png)

2022-05-30 15:10 UTC, Olexandr6 approved these changes
Good job🔥

2024-11-22 22:34 UTC, closed without merging