God bless at least this time
mate-academy/layout_miami pull request #1123
Opened 2022-05-30 12:54 UTC by Havrysh

More than welcome to read some remarks

2022-05-31 15:09 UTC, ArtemTopolskyi requested changes
add link to the demo page

2022-06-02 07:53 UTC, Havrysh commented
> 

deployed

2022-06-03 09:28 UTC, Bohdan-Maksymiuk requested changes
* добав валідація на форму - зараз вона пуста проходить
* перевір всі лінки на лого в демці

https://user-images.githubusercontent.com/94289038/171827919-23a634a0-4af6-4501-b4db-30a4e4cc6ffa.mov

* прибери скрол в менюшці
![Screenshot 2022-06-03 at 12 24 37](https://user-images.githubusercontent.com/94289038/171827965-5feb69d3-b18f-4855-83f6-1aae86703dc1.png)
* поправ тут номери - вони мають появлятися чітко коли я наводжу на телефон + 
 там два різнці номери - а посилання на один

https://user-images.githubusercontent.com/94289038/171828074-72ba5407-bb69-4d13-a19c-49c20128774f.mov

2022-06-03 10:19 UTC, Havrysh commented
> 

на рахуное номерів не впевнений що виправив правильно, підкажіть як додати ссилку на них якщо це псевдоелементи

2022-06-04 13:17 UTC, ArtemTopolskyi requested changes
при первом открытии страницы не работает скролл на странице

2022-06-08 11:06 UTC, ArturErmolenko requested changes
- Page shouldn't be reloaded on form submit (https://developer.mozilla.org/en-US/docs/Web/API/Event/preventDefault)
- Add hover effects for this block
<img width="1119" alt="Screenshot 2022-06-08 at 14 02 38" src="https://user-images.githubusercontent.com/94292654/172601102-528ca644-4171-486e-93e4-8cea87c42583.png">

- Add hover effects for address and phone numbers, not just cursor pointer
<img width="569" alt="Screenshot 2022-06-08 at 14 03 49" src="https://user-images.githubusercontent.com/94292654/172601332-593ca4d5-d00b-4f42-b41f-7f01b794696e.png">

2022-06-08 19:59 UTC, marina-tilniak approved these changes
Well done 🚀

2024-12-11 13:33 UTC, closed without merging