THE MET lending is done
mate-academy/layout_miami pull request #1170
Opened 2022-06-20 08:55 UTC by Kras4iy

[DEMO LINK](https://Kras4iy.github.io/layout_miami/)

2022-06-20 11:46 UTC, oleksandr-kotliarov requested changes
![image](https://user-images.githubusercontent.com/106398574/174593423-c03c0911-312a-400d-94fe-f8358ba0764c.png)
![image](https://user-images.githubusercontent.com/106398574/174593456-4bff9695-4274-40d1-960b-cd8f0329ca9f.png)

![image](https://user-images.githubusercontent.com/106398574/174593617-b197f5f0-298d-4ca3-945e-50d7536c8766.png)
Якось різко з'являється

![image](https://user-images.githubusercontent.com/106398574/174593714-a0354c25-b652-470d-9ab6-af4a8ecd0930.png)

![image](https://user-images.githubusercontent.com/106398574/174594735-d7f62f5d-ac1b-4134-9fab-eb0fea2e33cd.png)
![image](https://user-images.githubusercontent.com/106398574/174594100-abb5c38a-0730-4336-83cb-fbf32b687e79.png)

2022-06-20 11:46 UTC, oleksandr-kotliarov commented on src/styles/blocks/button.scss
> +  transition: background-color 0.3s;
Бачив коментар від ментора, що якщо час на всій сторінці однаковий, то краще винести у змінну

2022-06-20 13:54 UTC, oleksandr-kotliarov approved these changes
Все добре

2022-06-20 14:30 UTC, VETALEK requested changes
Here it the style for focused field:

<img width="643" alt="image" src="https://user-images.githubusercontent.com/55802630/174624278-67b2ea21-8548-40be-ab7e-b2a2a9424d68.png">

And here is your one:

<img width="427" alt="image" src="https://user-images.githubusercontent.com/55802630/174624387-c5eb2579-2582-41f5-8d26-6696db520b0b.png">

2022-06-20 14:32 UTC, VETALEK requested changes
This happens when i decrease the screen height 😭😭😭

<img width="1280" alt="image" src="https://user-images.githubusercontent.com/55802630/174624695-7cf9c219-dffe-43b5-a597-343781d90b47.png">

2022-06-21 07:10 UTC, VETALEK requested changes
Can't scroll, i suppose it has `position: fixed`, try using absolute instead

<img width="721" alt="image" src="https://user-images.githubusercontent.com/55802630/174738060-259eb9b2-7032-4121-8ce1-e05a687aa3b0.png">

2022-06-21 09:16 UTC, VETALEK approved these changes
https://css-tricks.com/almanac/properties/s/scrollbar/ check this topic 😉

2026-04-28 18:08 UTC, closed without merging