MyBike
mate-academy/layout_miami pull request #1211
Opened 2022-06-21 18:36 UTC by vitalii-labunskyi

[DEMO LINK](https://vitalii-labunskyi.github.io/layout_bike/)

2022-06-23 08:50 UTC, vitalii-labunskyi commented
@marina-tilniak Оновив все, але не можу зрозуміти чому в [DEMO LINK](https://vitalii-labunskyi.github.io/layout_bike/) не підтягує...

2022-06-24 09:02 UTC, marina-tilniak requested changes
для того, щоб за посиланням на GitHub все оновилося потрібно зробити deploy. Але у тебе все добре так як я бачу зміни. Лишилоися виправити форму, вона при submit не поаинна переходитити на 404

2022-06-25 18:46 UTC, marina-tilniak requested changes
ще трохи не так)
textarea потрібно закривати у тому самому рядку
<img width="573" alt="image" src="https://user-images.githubusercontent.com/94261494/175786559-3a4c4170-a661-4a26-bdc7-579183918a1e.png">
чому кнопка на submit форми відкриває нову вкладку?
15-й пункт чек листа 
Page shouldn't be reloaded on form submit (https://developer.mozilla.org/en-US/docs/Web/API/Event/preventDefault)

2022-06-25 18:46 UTC, marina-tilniak reviewed
<img width="558" alt="image" src="https://user-images.githubusercontent.com/94261494/175786644-01b7abdd-bd5d-4757-b7fc-b5fed3fd28ab.png">

2022-06-27 09:18 UTC, ArtemTopolskyi requested changes
![image](https://user-images.githubusercontent.com/57574816/175904983-d5d10e15-a735-406a-9608-51f51e9c2822.png)
этому элементу лучше добавить padding

![image](https://user-images.githubusercontent.com/57574816/175905158-a81f6b95-f7ff-4c78-9cd0-b0a63eb43022.png)
страница не должны растягиваться на широких экранах, центрируй контент, чтобы его удобно было читать на широких устройствах

2022-06-29 13:03 UTC, aliceblunt8 approved these changes

2022-07-03 13:53 UTC, closed without merging