Develop
mate-academy/layout_miami pull request #1257
Opened 2022-07-18 10:01 UTC by p-omogit-e

[DEMO LINK](https://p-omogit-e.github.io/layout_miami/)

2022-07-20 10:39 UTC, ArturErmolenko requested changes
Check again [Checklist](https://github.com/mate-academy/layout_miami/blob/master/checklist.md)

1. Fix phone number
<img width="836" alt="Screenshot 2022-07-20 at 13 35 47" src="https://user-images.githubusercontent.com/94292654/179962342-c3eeb5c9-0bac-4a6e-b0b4-b7e23e0f3c95.png">

2.When you click on phone icon or phone number in contacts section, make sure that there is no 404 error, make it a real link to start a call on device
Same when you click on logo. There shouldn't be any error.

3.Location-related addresses / links / images should open google maps in a new tab target="_blank"
4.Form shouldn't be submitted if some of the fields are not filled
Page shouldn't be reloaded on form submit (https://developer.mozilla.org/en-US/docs/Web/API/Event/preventDefault)

2022-07-29 07:56 UTC, alexandra-protyanova commented
Давай сделаем выезжающую менюшку немного плавнее)
![Снимок экрана 2022-07-29 в 10 53 20](https://user-images.githubusercontent.com/102182808/181712035-900391ba-ff43-4421-8016-dc70dbb2ab50.png)
![Снимок экрана 2022-07-29 в 10 53 25](https://user-images.githubusercontent.com/102182808/181712048-611ca435-4488-47a0-a77e-4266fc813e1d.png)
И добавим хавер эффекты на картинки и ссылочки

 
![Снимок экрана 2022-07-29 в 10 53 34](https://user-images.githubusercontent.com/102182808/181712141-89edc42f-d823-41e5-b2bb-670e888ee3a5.png)
Когда я отправляю форму меня редиректит на 404 и страница не должна перезаружаться

2022-07-29 07:56 UTC, alexandra-protyanova requested changes
fix comments

2022-08-10 11:47 UTC, alexandra-protyanova requested changes
0.5s для менюшки это всё ещё мало.
Добавь что-нибудь при хавере на элементы которые я скринила 
и форма всё ещё редиректит на 404

2025-12-17 21:32 UTC, closed without merging