Develop
mate-academy/layout_miami pull request #130
Opened 2020-03-11 15:56 UTC by FaychakA

[DEMO LINK](https://FaychakA.github.io/layout_miami/)

2020-03-12 10:16 UTC, 8hokage requested changes

2020-03-12 10:16 UTC, earthhuman41 commented on src/styles/main.scss
>  }
I dont think you need specify all this styles to each tag

2020-03-12 15:49 UTC, 8hokage reviewed
Пройдись табом и поубирай синие outline, и замени на кастомные с :focus

2020-03-12 15:49 UTC, earthhuman41 commented on src/index.html
> +    </div>
1. Телефон должен быть ссылкой такого вида:
`<a href="tel:123-456-7890">123-456-7890</a>`
Тогда пользователь сможет по ней кликнуть, если он с телефона на страничке, и его сразу перебросит в приложение для звонков

2020-03-12 15:49 UTC, earthhuman41 commented on src/styles/info.scss
> +  & a {
не стилизуй теги

2020-03-12 15:50 UTC, earthhuman41 commented
Лучше растянуть на весь экран
<img width="780" alt="Screen Shot 2020-03-12 at 5 49 16 PM" src="https://user-images.githubusercontent.com/50083082/76539751-d5e3e180-6489-11ea-8772-3720243acfc2.png">

2020-03-13 09:49 UTC, 8hokage approved these changes

2026-01-12 09:43 UTC, closed without merging