header desktop and mobile version was created
mate-academy/layout_miami pull request #1319
Opened 2022-07-28 13:16 UTC by vladgusakovskiy

- [DEMO LINK](https://vladgusakovskiy.github.io/layout_miami/)

2022-07-29 13:59 UTC, MaksimusCRS requested changes
Меню не работает, при нажатии на ссылку, не скролит к нужной секции

При клике на лого - открывается страница с ошибкой

2022-08-02 19:20 UTC, Andr1yK requested changes
Щось не так з сабмітом форми

https://user-images.githubusercontent.com/86183007/182455140-d700f0ab-51fc-4e6e-b2b6-f32e30a2d882.mov

[Пункт 4
](https://github.com/mate-academy/layout_miami/blob/master/checklist.md)<img width="214" alt="image" src="https://user-images.githubusercontent.com/86183007/182455525-10d622f9-82a2-4288-b9b1-7d862e62a0e0.png">

[Пункт 9
](https://github.com/mate-academy/layout_miami/blob/master/checklist.md)

https://user-images.githubusercontent.com/86183007/182455822-79871aeb-a601-4acf-9221-fe97eb40384a.mov

В блоці The Details можна додати хавери для фото [Пункт 10
](https://github.com/mate-academy/layout_miami/blob/master/checklist.md)

2022-08-05 13:45 UTC, Andr1yK requested changes
[Пункт 15 в чеклісті](https://github.com/mate-academy/layout_miami/blob/master/checklist.md)

2022-08-08 13:16 UTC, MaksimusCRS approved these changes
GJ!

2022-10-15 07:58 UTC, closed without merging