Develop1
mate-academy/layout_miami pull request #1418
Opened 2022-08-30 09:46 UTC by p-omogit-e

DEMO LINK](https://p-omogit-e.github.io/layout_miami/)

2022-09-01 10:18 UTC, valerii-derkach requested changes
-додай favicon
-форма не повинна переходити на сторінку 404
-виправ поведінку меню відносно зображень
https://user-images.githubusercontent.com/102413088/187890676-c6df856a-d937-4823-89c7-472331575842.mov

2022-09-03 15:26 UTC, SanyaBratashchuk requested changes
Після самбіту форма має очищатись і більше нічого відбуватись не має

2022-09-13 10:04 UTC, marina-tilniak requested changes
щось не так з якістю цього зображення
<img width="1439" alt="image" src="https://user-images.githubusercontent.com/94261494/189873279-579c0d73-9a25-4748-8817-62a43e697b85.png">
і ці виглядвють не якісно, потрібно або зменшити їх розмір на такому екрані або взяти краще розширення
<img width="887" alt="image" src="https://user-images.githubusercontent.com/94261494/189873472-7f75dffd-2db6-45c1-a760-f6621c9c3bb4.png">

2023-01-08 10:02 UTC, nazarmatsevych approved these changes
Try to fix this image
![image](https://user-images.githubusercontent.com/80700247/211190161-fcf26bd7-86e2-4569-b515-d87898eedbb6.png)

2025-12-17 21:32 UTC, closed without merging