BOSE done
mate-academy/layout_miami pull request #1667
Opened 2022-11-03 08:01 UTC by Pallaci0

2022-11-03 18:52 UTC, AlisaVlasova requested changes
Додай демо лінк, будь ласка

2022-11-03 18:52 UTC, AlisaVlasova commented on src/index.html
> +        </h1>
```suggestion
        <h1 class="header__title">
         The world shades.<br>
         Your music shines.
        </h1>
```
поправ кодстайл і форматування по всім файлам

2022-11-04 08:38 UTC, Pallaci0 commented on src/index.html
> +        </h1>
ок, виправлю

2022-11-04 08:52 UTC, Pallaci0 commented on src/index.html
> +        </h1>
"поправ кодстайл і форматування по всім файлам" Не знаю в яких інших файлах треба було виправляти але, але в index.html поправив

2022-11-05 08:51 UTC, AlisaVlasova reviewed
демка все ще не працює(

2022-11-05 08:51 UTC, AlisaVlasova commented on src/index.html
> +    <main>
```suggestion
    </div>
    
    <main>
```

2022-11-05 08:51 UTC, AlisaVlasova commented on src/index.html
> +    <div class="page__menu menu__content page__menu--skroll" id="menuopen">
```suggestion
    </header>

    <div class="page__menu menu__content page__menu--skroll" id="menuopen">
```

2022-11-05 08:51 UTC, AlisaVlasova commented on src/index.html
> +      <div class="menu__container--right">
```suggestion
      <div class="menu__container--right">
```

2022-11-05 08:51 UTC, AlisaVlasova commented on src/index.html
> +      </section>
```suggestion
          </div>
        </div>
       </div>
     </section>
```

2022-11-06 13:23 UTC, Pallaci0 commented on src/index.html
> +      </section>
Там якісь проблеми с тим demo link я пробував вирішити з ментором але не вийшло, я тебе тегнув в переписці де ми з ним це рішали

2022-11-07 14:51 UTC, closed without merging