HTML built, header stylized
mate-academy/layout_miami pull request #1823
Opened 2022-12-08 15:51 UTC by Sergei-Nikolaienko

https://Sergei-Nikolaienko.github.io/layout_miami/

2022-12-09 09:40 UTC, liliia-livandovskaya requested changes
Deploy project <img width="1118" alt="Screenshot 2022-12-09 at 11 40 15" src="https://user-images.githubusercontent.com/104769168/206672274-000d06e0-a31c-4380-b8df-128c42310fd7.png">

2022-12-11 18:56 UTC, OlEzhA0 requested changes
привіт
записав тобі відео фідбек по твоїй роботі
[link](https://drive.google.com/file/d/1ujwPBwdKxzxI8yiXY1DmAnK69mCdkAST/view?usp=sharing)
якшо немає доступу - пінгуй мене в fe_chat

2022-12-12 05:30 UTC, Sergei-Nikolaienko commented
> 

Дякую за фідбек - в тому коміті зробив тільки хедер (в завданні казали кожен блок на перевірку кидати), зараз запушу все інше

2022-12-13 15:47 UTC, witflash commented
Hey! You lost some requirements:
> 8. Pictures in Gallery should increase on hover
> 9. Location-related addresses / links should open google maps in a new tab target="_blank"
> 10. Apply :hover effect for images on page (testimonials / gallery, other sections).
> 17. Fix menu for small screens (if there is not enough space for all the menu items)

2022-12-13 16:28 UTC, witflash requested changes
Hey! 
Pay attention to my comments.

And you lost some requirements:
> 8. Pictures in Gallery should increase on hover
> 9. Location-related addresses / links should open google maps in a new tab target="_blank"
> 10. Apply :hover effect for images on page (testimonials / gallery, other sections).
> 17. Fix menu for small screens (if there is not enough space for all the menu items)

2022-12-13 16:28 UTC, witflash commented on src/scripts/main.js
> +const toTopBtn = document.getElementById('topButton');
If you want to use some elements in JS, you better add `js-{some-name}` class and use it in your script.
Here is better do smth like this:
```
const toTopBtn = document.querySelector('.js-top-button');
```

2022-12-13 16:28 UTC, witflash commented on src/styles/blocks/card.scss
> +  }
```suggestion
  @include onIpad {
    width: 392px;
  }

  @include onDesktop {
    width: 324px;
  }
```

2022-12-13 16:28 UTC, witflash commented on src/styles/blocks/compare.scss
> +      &:last-child {
```suggestion
      margin-bottom: 48px;
      
      &:last-child {
```

2022-12-13 16:28 UTC, witflash commented on src/styles/blocks/features.scss
> +        display: block;
You don't need to duplicate `content` and `display` rules in media queries if they did not change.

2022-12-13 16:28 UTC, witflash commented on src/styles/utils/_vars.scss
> +  --form-background: #f8f8fa;
It's better to name it:
```
--color-primary
--color-background or --color-secondary
```

2022-12-13 16:28 UTC, witflash commented on src/styles/blocks/title.scss
> +  letter-spacing: -1.5px;
Do not use non-integer values. Use here `1` or `2` px.

2022-12-13 16:28 UTC, witflash commented on src/styles/blocks/page.scss
> +    a {
Do not use CSS rules for tags. Use it for necessary blocks and elements.

2022-12-13 16:28 UTC, witflash commented on src/styles/blocks/menu.scss
> +  z-index: 1000;
Do you really need such a big z-index? If you do not have a large project, you can use smaller values (e. g. from 1 to 10)

2022-12-13 16:28 UTC, witflash commented on src/styles/blocks/header.scss
> +    &-image {
Don't divide elements' names. Use full name: 
```
&__logo-image {
```

2022-12-15 09:13 UTC, witflash requested changes
Привіт!
А по цим вимогам із завдання я не бачу змін:

> And you lost some requirements:
> > 8. Pictures in Gallery should increase on hover
> > 9. Location-related addresses / links should open google maps in a new tab target="_blank"
> > 10. Apply :hover effect for images on page (testimonials / gallery, other sections).
> > 17. Fix menu for small screens (if there is not enough space for all the menu items)

Якщо є якісь питання, чи щось не зрозуміло, можеш звернутись в канал fe_chat

2022-12-17 17:13 UTC, ivanchuk-yurii commented
should be in one line
<img width="875" alt="image" src="https://user-images.githubusercontent.com/53611910/208253200-e233fcd9-e3e1-4a65-8d28-937717be9341.png">
in one line 
<img width="684" alt="image" src="https://user-images.githubusercontent.com/53611910/208253254-f1a542a8-7b53-481a-8304-7edb06b2ccf4.png">
fix hover
https://user-images.githubusercontent.com/53611910/208253393-877beadd-9255-4791-92da-6ffb23831d7a.mov
make all input in form required. don't reload page on form submit

2022-12-19 12:01 UTC, liliia-livandovskaya requested changes
Great job! Your landing looks awesome 👍 
There are two more things to improve:

1. Add `transition-duration` on hover

2. Pay attention to the title and fix it according to the mockup 
<img width="353" alt="Screenshot 2022-12-19 at 13 52 58" src="https://user-images.githubusercontent.com/104769168/208421377-c64f518d-27f2-4e1e-960c-ac68931ffbf5.png">

2022-12-20 19:31 UTC, witflash approved these changes
Pretty well!
Well done! 👍

2023-01-12 09:58 UTC, closed without merging