Develop
mate-academy/layout_miami pull request #1983
Opened 2023-01-17 19:51 UTC by VladGraund

[DEMO LINK](https://VladGraund.github.io/layout_miami/)

2023-01-18 20:49 UTC, witflash requested changes
1. You do not have form validation
![image](https://user-images.githubusercontent.com/25587299/213290861-6e5c8e82-caee-4604-b30d-f549799316dc.png)

2. You need to add a link to the map for the address
![image](https://user-images.githubusercontent.com/25587299/213290992-622f7be7-304d-4990-85a9-30aa05bcfcbd.png)

3. I think the first block should have the same width as the next
![image](https://user-images.githubusercontent.com/25587299/213291250-439a433c-055a-4d83-98d9-65aae62b714d.png)

4. Could you add the scroll to the menu for a small mobile screen?
![image](https://user-images.githubusercontent.com/25587299/213291410-e8f479b1-b5bc-4f8a-b2a7-ee2e7275ad5b.png)

2023-01-19 08:39 UTC, VladGraund commented
> 1. You do not have form validation
>        ![image](https://user-images.githubusercontent.com/25587299/213290861-6e5c8e82-caee-4604-b30d-f549799316dc.png)
> 
>     2. You need to add a link to the map for the address
>        ![image](https://user-images.githubusercontent.com/25587299/213290992-622f7be7-304d-4990-85a9-30aa05bcfcbd.png)
> 
>     3. I think the first block should have the same width as the next
>        ![image](https://user-images.githubusercontent.com/25587299/213291250-439a433c-055a-4d83-98d9-65aae62b714d.png)
> 
>     4. Could you add the scroll to the menu for a small mobile screen?
>        ![image](https://user-images.githubusercontent.com/25587299/213291410-e8f479b1-b5bc-4f8a-b2a7-ee2e7275ad5b.png)

Point n.4: old phone height = minimum 568px, but you show me height of 430-440px. Why?

2023-01-23 08:57 UTC, OlEzhA0 requested changes
your first screen should be full height
<img width="1792" alt="Screenshot 2023-01-23 at 10 53 32 AM" src="https://user-images.githubusercontent.com/60295799/213999172-5290b884-dcb9-4a2e-9032-c8185325bbfb.png">

2. add some hover effects to your gallery 
3. open google maps in new tab
<img width="307" alt="Screenshot 2023-01-23 at 10 56 39 AM" src="https://user-images.githubusercontent.com/60295799/213999810-16de5f9f-684e-4bed-a8e7-75c623dd3e2a.png">
4. when submitted form, it's redirected me to 405 page

2023-01-23 14:37 UTC, VladGraund commented
>     2. add some hover effects to your gallery
What do You mean?

2023-01-27 08:49 UTC, vlad-demchuk requested changes
button should submit the form.
 because now fields aren't required
<img width="363" alt="image" src="https://user-images.githubusercontent.com/102411130/215045195-5058f687-b73b-4fde-8c78-798285c64e20.png">

2023-01-27 08:53 UTC, VladGraund commented
> button should submit the form. because now fields aren't required <img alt="image" width="363" src="https://user-images.githubusercontent.com/102411130/215045195-5058f687-b73b-4fde-8c78-798285c64e20.png">

Sorry but, I don't know how to implement it.

2023-01-28 09:06 UTC, nazarmatsevych requested changes
Pls ask all of your questions in fe_chat, there you will be able to get an answer much faster

To avoid reloading the page and to clear the form you have to add simple JavaScript code:

`const form = document.querySelector('.form');

form.addEventListener('submit', (event) => {
  event.preventDefault();
  form.reset();
});`

2023-01-29 12:33 UTC, Volodymyr-Melnyk-Fron10der requested changes
1. Check horizontal paddings for all blocks - it should be same
**Your view:**
![image](https://user-images.githubusercontent.com/122989585/215325607-7f0acf3c-1b8d-4509-875f-c5c29b66a356.png)
![image](https://user-images.githubusercontent.com/122989585/215326129-ee10d6f6-7136-4b44-9daa-31d7a1430196.png)
**Design:** 
![image](https://user-images.githubusercontent.com/122989585/215326158-ed1fd396-addb-4b3f-bec8-326ebf4c3f00.png)
2. Add hover on card bike image
![image](https://user-images.githubusercontent.com/122989585/215326361-4dbf2cee-5ecc-4fc3-ae57-0a516c9ff2fb.png)
![image](https://user-images.githubusercontent.com/122989585/215326375-36d98a11-c26d-444b-8dd6-0ff88b6a8112.png)

2023-01-30 13:41 UTC, IvanFesenko requested changes
Good job. Fix this bug
After click on any item in menu then click on logo - page can't be scrolled more
https://user-images.githubusercontent.com/61904995/215492906-7da170e9-3c71-4511-9326-f6b28c0b84da.mp4

2023-01-30 14:04 UTC, VladGraund commented
> Good job. Fix this bug After click on any item in menu then click on logo - page can't be scrolled more https://user-images.githubusercontent.com/61904995/215492906-7da170e9-3c71-4511-9326-f6b28c0b84da.mp4
 I'm sorry but, i don't know how to fix that.

2023-01-31 15:29 UTC, IvanFesenko requested changes
Good job.
Found more two bugs. Hover on menu works outside items. Check video

https://user-images.githubusercontent.com/61904995/215803145-292e888b-c3b4-4c9e-b9d7-118a3285bdab.mp4

Also form didn't much design

![2023-01-31_17h26_02](https://user-images.githubusercontent.com/61904995/215803538-5b8cb97c-5912-4329-a0d4-5ebe61006267.png)

2023-02-01 17:40 UTC, etojeDenys requested changes

2023-02-01 17:40 UTC, etojeDenys commented on src/index.html
> +              <h5 class="bike-contact__info-label"><a href="https://goo.gl/maps/8mU59QcDNSWuFvXC9" target="_blank">400 first ave.<br>suite 700<br>Minneapolis, MN 55401</a></h5>
you can add a new line between bike-contact__info div`s for better readability

2023-02-01 17:40 UTC, etojeDenys commented on src/index.html
> +          <div class="bike-goods__card grid__item--5-8--laptop grid__item--2-5--tablet">
same here, we can add a new line

2023-02-04 10:47 UTC, nazarmatsevych approved these changes

2025-02-28 14:01 UTC, closed without merging