The first block of miami
mate-academy/layout_miami pull request #2014
Opened 2023-01-27 22:45 UTC by olya-girnyak

[DEMO LINK](https://olya-girnyak.github.io/layout_miami/)

2023-01-28 13:02 UTC, agniya-i requested changes
Good job!

1. Pay attention that logo shouldn't follow 404 page 
2. Add `cursor: pointer` to phone icon 

Re-request after finish whole page

2023-02-02 11:27 UTC, Anastasiia-Svintsova requested changes
- All external links should open in a new tab. Fix it, please

https://user-images.githubusercontent.com/99403198/216312060-a8529ee2-d1c1-48d9-bbc3-86f66a3d0f5d.mov

- Same for addresses here 
<img width="587" alt="image" src="https://user-images.githubusercontent.com/99403198/216312517-2a7fd006-231b-44d3-afb6-8fcc628de092.png">


- The form shouldn't reload after submitting

https://user-images.githubusercontent.com/99403198/216312358-1f1d0f1c-8832-4d73-9af6-2feddf7edddd.mov

- Check the font size for the buttons on small screens
<img width="587" alt="image" src="https://user-images.githubusercontent.com/99403198/216312790-b9430869-4522-420c-9d98-9d3bdcb36548.png">

2023-02-03 16:19 UTC, slavanosatskyi approved these changes

2023-02-03 16:19 UTC, slavanosatskyi commented on src/styles/blocks/button.scss
> +  transition: all 0.3s;
0.3s this is something that is used all over the styles. It would be better to move such values to variables as well

2024-01-17 14:59 UTC, closed without merging