header
mate-academy/layout_miami pull request #2020
Opened 2023-01-28 19:23 UTC by maxonshev

[DEMO LINK](https://maxonshev.github.io/layout_miami/)

2023-01-29 09:21 UTC, qoa11a requested changes
nice start! keep on going 👍

2023-01-30 18:49 UTC, Volodymyr-Melnyk-Fron10der requested changes
Hi, nice work
1. Add favicon 
![image](https://user-images.githubusercontent.com/122989585/215567331-f51217c6-755c-4307-9886-ed4b440b5d2c.png)
2. Menu is not scrollable when it is not enough space
![image](https://user-images.githubusercontent.com/122989585/215567447-2dda7e2e-e10e-4718-a46d-cb5a1045e335.png)
3. It is better to request review after each implemented page block
![image](https://user-images.githubusercontent.com/122989585/215567701-a7e6c4f9-ade2-42ea-b6b1-dfd6065f1c49.png)

2023-01-31 20:20 UTC, maxonshev commented
> Hi, nice work

> 2. Menu is not scrollable when it is not enough space
>    ![image](https://user-images.githubusercontent.com/122989585/215567447-2dda7e2e-e10e-4718-a46d-cb5a1045e335.png)

як зробити щоб меню скролилось? В проекті miami, який робив Михайло по відео, воно теж не скролиться, коли місця недостатньо

2023-02-04 13:18 UTC, SanyaBratashchuk requested changes
1. Make scale smaller to avoid overlapping 
![image](https://user-images.githubusercontent.com/97547824/216769632-4e977045-a215-48f6-b9ef-175b0ba25b19.png)
2. Add some hover effects for these links (change color etc.)
![image](https://user-images.githubusercontent.com/97547824/216769825-7909dbcf-a9ea-4757-97d2-d83ac954a960.png)

2023-02-05 11:12 UTC, SanyaBratashchuk approved these changes

2025-03-07 10:51 UTC, closed without merging