Created header with menu
mate-academy/layout_miami pull request #2026
Opened 2023-01-30 13:21 UTC by Zelinskyi-Serhii

https://Zelinskyi-Serhii.github.io/layout_miami/

2023-02-11 13:36 UTC, Yevhenii0536 commented
![image](https://user-images.githubusercontent.com/110053436/218260809-04c933eb-3df1-421d-a86b-e99378c8e128.png)
your bg-color doesn't as in mock-up

2023-02-11 13:39 UTC, Yevhenii0536 commented
![image](https://user-images.githubusercontent.com/110053436/218260998-3030adf8-ce64-4810-b70c-74974d731555.png)
this is must be as link, wich will bring users to page with another product with same category

2023-02-11 13:43 UTC, Yevhenii0536 commented
![image](https://user-images.githubusercontent.com/110053436/218261178-ebcda693-1b29-4938-97dc-86aecd8d6166.png)
in mock-up title of products must have left position. in yours - title have position center

2023-02-11 13:50 UTC, Yevhenii0536 requested changes
pls, fix issues which i was write

2023-02-13 12:01 UTC, Yevhenii0536 approved these changes

2023-02-13 15:48 UTC, Andr1yK requested changes
bug on submit form

https://user-images.githubusercontent.com/86183007/218504802-4a922e94-7ccd-42bd-9942-3dfc23f18ba2.mov

add hovers

<img width="213" alt="image" src="https://user-images.githubusercontent.com/86183007/218505021-6bff5b25-503b-44e1-81ba-c901477bb463.png">

2023-02-13 15:48 UTC, Andr1yK commented on src/blocks/button.scss
> +    }
looks weird)

2023-02-18 15:05 UTC, Andr1yK requested changes
fix links and form (points 13-15 in the checklist)

https://user-images.githubusercontent.com/86183007/219872944-34f42048-9f40-4a05-a074-f9eb6d8b378b.mov

2023-02-22 12:45 UTC, sergii-nosachenko requested changes
Some issues:
- check raster image format (for photos JPEG is preferable)
- check the images ration after the tablet breakpoint
   
![Bose (1)](https://user-images.githubusercontent.com/54940595/220623201-25d2eefc-6127-44e3-a6a9-2bd86c73113c.png)

- check menu z-index

https://www.loom.com/share/8b1741f4708140faa1827d7c241f2905

2023-02-22 12:45 UTC, sergii-nosachenko commented on src/blocks/header.scss
> +  background-image: url(../images/headerMobileSvg.svg);
Why do you use vector format for the raster image?

2023-02-23 11:30 UTC, sergii-nosachenko approved these changes
Good work 👍

2023-07-12 20:29 UTC, closed without merging