created header and first block of main width adaptation bouth
mate-academy/layout_miami pull request #2069
Opened 2023-02-08 12:15 UTC by vadosik15

DEMO LINK](https://vadosik15.github.io/layout_miami/)

2023-02-10 13:37 UTC, Lilu580 reviewed
Check cheklist 1.you have no favicon,3.All Logos on the page should be links to home page 6.Same when you click on logo. There shouldn't be any error.9.Location-related addresses / links should open google maps in a new tab target="_blank.14.Form shouldn't be submitted if some of the fields are not filled.15.Page shouldn't be reloaded on form submit.16Add a smooth scroll for the whole page.19Remember to reset default margins for headings (h1, h2, h3, etc.).

2023-02-10 13:37 UTC, Lilu580 commented on src/styles/blocks/icons.scss
> +      width: 24px;
on table you should use another image for burger

2023-02-10 13:37 UTC, Lilu580 commented on src/styles/mixins.scss
> +}
you can do this project without this mixin,just with method mobile-first

2023-02-10 13:37 UTC, Lilu580 commented on src/styles/emets/placeholder.scss
> +  padding-top: 8px;
you have this paffing for elements of contact block,this elements should have margins bottom

2023-02-14 11:35 UTC, illiarerun requested changes
- checklist 6th item
![image](https://user-images.githubusercontent.com/37161315/218725885-b1fb028a-f458-4b83-857d-8e71c28197b7.png)

- checklist 5th item
![image](https://user-images.githubusercontent.com/37161315/218725969-a937eb9d-5625-41b5-ae6a-c0414313655e.png)

- add transitions here
![image](https://user-images.githubusercontent.com/37161315/218726185-92a9e863-d0fa-475b-a2bc-fe92b6bbb7c3.png)

- and here
![image](https://user-images.githubusercontent.com/37161315/218726240-55dcadf8-40ae-4e7f-bf9c-c04a584ab4bf.png)

2023-02-14 16:48 UTC, closed without merging

2023-02-19 12:35 UTC, valeriiayarzhemska reviewed
platform sent me here, but its closed