bike project
mate-academy/layout_miami pull request #2148
Opened 2023-02-26 17:30 UTC by yuron-maker

Sorry. I did not notice that it was necessary to do block by block
[DEMO LINK](https://yuron-maker.github.io/layout_miami/)

2023-02-28 07:55 UTC, tetiana-ivanchenko requested changes
https://github.com/mate-academy/layout_miami/blob/master/checklist.md
fix according checklist points:
1, 4, 8, 9. 10, 14, 15

also form submitting shouldn't change the link
check if all your styles according to mockup
![image](https://user-images.githubusercontent.com/59209337/221789213-2c10ce04-cb7f-48d0-a92d-75638b99bd65.png)

2023-03-01 12:24 UTC, sTorba24 requested changes
Fix previous comment
![image](https://user-images.githubusercontent.com/55200530/222138570-855cee43-2fff-44d4-b56d-3e88d9a5c260.png)

2023-03-01 16:04 UTC, SerhiiKirik approved these changes
Good job 🔥 

but i recommend you use scroll-behavior: smooth; in html tag
https://user-images.githubusercontent.com/91411692/222194819-878e533a-75ef-4b26-bc02-d40c11102979.mov

2023-03-01 16:04 UTC, SerhiiKirik commented on src/index.html
> +              </div>
```suggestion
      </section>
      
      <section class="details" id="details">
        <div class="container">
          <h2 class="page__section-title">The details</h2>
          
          <div class="details__content">
            <div class="grid details__section">
              <div class="grid__item--desktop-1-8 grid__item--tablet-1-4">
                <div class="details__photo-container">
                  <img
                    src="./images/photos/image 12.png"
                    alt="image12"
                    class="details__photo"
                  >
                </div>
              </div>
              
              <div class="grid__item--desktop-9-12 grid__item--tablet-5-6">
                <div class="details__photo-container">
                  <img
                    src="./images/photos/image 8.png"
                    alt="image8"
                    class="details__photo"
                  >
                </div>
              </div>
              
              <div class="grid__item--full">
                <h3 class="details__subtitle">Auto Unlock</h3>
                
                <p class="details__text">
                  The app senses when you're nearby to unlock automatically. GPS
                  tracking so you know where your bike is and can track it
                  anytime.
                </p>
              </div>
              
```

2023-03-01 16:04 UTC, SerhiiKirik commented on src/styles/blocks/_card.scss
> +    color: #fff;
create variables for all colors

```suggestion
    color: $c-white;
```

2024-10-30 17:21 UTC, closed without merging