miami_header
mate-academy/layout_miami pull request #2150
Opened 2023-02-26 21:12 UTC by postrygan

https://postryagn.github.io/layout_miami/

2023-03-01 15:52 UTC, SerhiiKirik requested changes
Well done 🚀 
But, please, deploy you changes with npm run deploy
Also, fix comments

2023-03-01 15:52 UTC, SerhiiKirik commented on src/styles/main.css
> +  margin: 0;
move to normalize file

```suggestion
body {
  background: #eee;
```

2023-03-01 15:52 UTC, SerhiiKirik commented on src/styles/main.css
> +  transition: transform 0.3s;
create variable for this
```suggestion
  transition: transform $transitionDuration;
```

2023-03-01 15:52 UTC, SerhiiKirik commented on src/styles/main.css
> +  color: #fff;
create variables for all colors
```suggestion
  color: $c-white;
```

2023-03-07 11:41 UTC, anstsot requested changes
The demo link isn't working. please deploy your changes
![image](https://user-images.githubusercontent.com/22824431/223412368-38ce53a6-d7a6-48b3-815e-13fff8c5919f.png)

2023-03-07 18:37 UTC, TarasHoliuk requested changes
Good start :+1: 
Please re-request review when entire task will be done
If you have any questions feel free to ask in chat

2023-03-18 16:13 UTC, closed without merging