mobile done
mate-academy/layout_miami pull request #2608
Opened 2023-10-25 13:02 UTC by aureliagorzna

- [DEMO LINK](https://aureliagorzna.github.io/layout_miami/)

2023-10-26 06:51 UTC, mvjl000 requested changes
I suppose that your solution is only for mobile devices for now. However it shouldn't have such a fixed values that it looks off on just a bit bigger mobile device. Your solution is tailored for 320px width and it's not a good way to handle RWD. Please try to improve it.

Besides of that:

- No favicon
- Wrong website title
- Menu doesn't open

2023-10-26 06:52 UTC, mvjl000 commented
Also please remember to get through the checklist and make sure that you implement all the requirements

2023-10-31 16:15 UTC, mbruhler requested changes
Hi,
For now changes are:
- page should fill the viewport on > 1260px viewports
- form should not reload page and should reset
- phone should show phone number
- menu doesn't work
-

2023-11-03 08:12 UTC, mvjl000 requested changes
I can't see any changes since previous reviews, please take not of our comments.

2023-11-06 07:48 UTC, JoyCoffeeAddict requested changes
Resolve previous issues.

2023-11-06 14:22 UTC, mbruhler requested changes
Your landing page is not compliant with the mockup and checklist. Please read it again carefully and style your website properly according to mockup.

2023-11-06 16:06 UTC, mbruhler requested changes
There are still issues
- 744px viewport is wrong 
![image](https://github.com/mate-academy/layout_miami/assets/21124163/87e62fcd-1d7b-473e-ab74-85ef6ce5dffd)
- 1260px viewport is wrong
![image](https://github.com/mate-academy/layout_miami/assets/21124163/070c3f9b-8b7a-484e-8d05-ac5d95e58f86)
- letter spacing is wrong on phone number
- header should be 100vh and properly sized so it's compliant with figma (you can't achieve proper alignemnt without 100vh) NOTE: despite mobile
- left padding on mobile is less than right 
![image](https://github.com/mate-academy/layout_miami/assets/21124163/a8e7d1b0-526e-49b2-9cd3-c9f4ab779535)

2023-11-07 08:10 UTC, JoyCoffeeAddict requested changes
1. Email link is not working (should open email app)
![image](https://github.com/mate-academy/layout_miami/assets/131690818/281d9fb3-c036-4b18-ad93-aef7e840b136)
Validation in the form is not working correctly 
![Animation](https://github.com/mate-academy/layout_miami/assets/131690818/57619db2-2d82-4ba3-a3c7-8dd5f9090f7e)
Look at the example from [documentation here](https://developer.mozilla.org/en-US/docs/Learn/Forms/Form_validation)
![image](https://github.com/mate-academy/layout_miami/assets/131690818/e37ae9af-35ca-48e4-94ed-dde8714048cb)

It is way better than before, so good job!

2023-11-07 09:08 UTC, JoyCoffeeAddict approved these changes

2025-01-18 14:18 UTC, closed without merging