MyBike
mate-academy/layout_miami pull request #2609
Opened 2023-10-26 09:49 UTC by Timi2424

[DEMO LINK](https://Timi2424.github.io/layout_miami/)

2023-10-26 12:32 UTC, mbruhler requested changes
Hi,
Good job on mobile version. There's still lots to do for other viewports

Also on mobile, last image (the bottom one) is too big.

2023-10-27 13:04 UTC, mvjl000 requested changes
- Textarea should have the same font as other inputs (currently it's monospace), send button shouldn't have default border, values of the form should clear on send
- You are missing the smooth scrolling,
- Both of these should be a call-able link 
![Screenshot 2023-10-27 at 15 00 59](https://github.com/mate-academy/layout_miami/assets/65824623/eca442d3-71ce-4041-9381-a78cf5a42ad5)
- Speaking of links (e.g. in the navigation) - they should have cursor pointer. All links should have cursor pointer.  In my opinion also clickable elements like buttons should have it too. It tells the user that he can interact with it. Maybe you would consider it? Tell me what you think ;)

2023-10-27 14:08 UTC, Timi2424 commented
> * Textarea should have the same font as other inputs (currently it's monospace), send button shouldn't have default border, values of the form should clear on send
> * You are missing the smooth scrolling,
> * Both of these should be a call-able link
>   ![Screenshot 2023-10-27 at 15 00 59](https://user-images.githubusercontent.com/65824623/278649716-eca442d3-71ce-4041-9381-a78cf5a42ad5.png)
> * Speaking of links (e.g. in the navigation) - they should have cursor pointer. All links should have cursor pointer.  In my opinion also clickable elements like buttons should have it too. It tells the user that he can interact with it. Maybe you would consider it? Tell me what you think ;)

2023-10-27 15:16 UTC, Timi2424 commented
from my side, the textarea has proper font family and send button has box shadow on hover

2023-10-30 09:35 UTC, mvjl000 requested changes
- Smooth scrolling, contact link (from menu) should head the user to the contact section

2023-10-31 07:45 UTC, mvjl000 requested changes
On tablet resolution the header title should be way lower
![Screenshot 2023-10-31 at 08 43 46](https://github.com/mate-academy/layout_miami/assets/65824623/3ab9dd54-a11b-46ce-a27f-edde265b7aba)

You are still missing cursor pointer for the links (see one of my previous reviews)

2023-10-31 08:50 UTC, mvjl000 requested changes
About those cursors...

2023-10-31 08:50 UTC, mvjl000 commented on src/styles/blocks/body.scss
> +    cursor: url(../images/cursor/cursorhover.png), auto;
Simply do:
```suggestion
    cursor: pointer;
```

2023-10-31 08:52 UTC, mvjl000 commented on src/styles/blocks/body.scss
> +    cursor: url(../images/cursor/cursorhover.png), auto;
By the way, it shouldn't be inside the hover {}

2023-10-31 09:44 UTC, mvjl000 requested changes
`cursor: pointer;`

2023-10-31 09:59 UTC, mvjl000 approved these changes

2024-07-05 16:52 UTC, closed without merging