Develop
mate-academy/layout_miami pull request #273
Opened 2020-09-10 15:34 UTC by andlap24

[DEMO LINK](https://andlap24.github.io/layout_miami/)

2020-09-12 13:12 UTC, AndriiManyak requested changes
Було б ще непогано, якщо ти відсортуєш свої css стилі так як це описано тут: https://codeguide.academy/html-css.html#css-order

2020-09-12 14:50 UTC, andlap24 commented on src/styles/contact.scss
> +  margin: 93px 0 88px;
так, це я дав маху. Перероблюю вже. Дякую

2020-09-13 15:03 UTC, AndriiManyak approved these changes

2020-09-14 11:51 UTC, danheim reviewed
Good start, almost done.

2020-09-14 11:51 UTC, danheim commented on src/index.html
> +            >
recommended to be a link

2020-09-14 11:51 UTC, danheim commented on src/index.html
> +        <h2 class="heading section__heading"  id="gallery">Gallery<span class="heading__crown"></span></h2>
add line breaks

2020-09-14 11:51 UTC, danheim commented on src/index.html
> +          <p class="gallery__caption"><a href="#" class="bright-color">Marina Palms</a> / North Miami Beach, FL 33162</p>
add line-breaks (adb)

2020-09-14 11:51 UTC, danheim commented on src/index.html
> +          <p class="gallery__caption"><a href="#" class="bright-color">Edition Residens</a> / Miami Beach, FL 33139 </p>
adb

2020-09-14 11:51 UTC, danheim commented on src/index.html
> +            <h3 class="consultation__title">How long have<br>you do yourself a gift?</h3>
рекомендую не использовать `<br/>` для переносов, у тебя есть CSS

2020-09-14 11:51 UTC, danheim commented on src/styles/about.scss
> +    transition: color $hover-duration;
иногда hover-duration может быть разной
рекомендую придумать добавить префикс по типу long quick etc

2020-09-14 11:51 UTC, danheim commented on src/styles/footer.scss
> +  background-position: center;
`background: ...`

2020-09-14 11:51 UTC, danheim commented on src/styles/footer.scss
> +  height: 359px;
use 8th values, for example: 360px

360 / 8 = 45

2020-09-15 12:00 UTC, danheim approved these changes
great
add cursor pointer to the buttons

2026-02-15 13:05 UTC, closed without merging