solution
mate-academy/layout_miami pull request #313
Opened 2020-12-01 12:34 UTC by Layrovell

[DEMO LINK](https://Layrovell.github.io/layout_miami/)

2020-12-03 14:06 UTC, Denchepornyuk requested changes
https://www.notion.so/Miami-c67f4ccee99a4e63aaed20d79500056e

2020-12-03 14:06 UTC, Denchepornyuk commented on src/styles/block.scss
> +  margin: 0 auto;
блок не моде мати зовнішні стилі

2020-12-03 14:06 UTC, Denchepornyuk commented on src/styles/contacts.scss
> +  margin: 0 auto;
п бем-у не можна на блок давати margin, а тут в тебе стилізація внутрішня і зовнішня, такого також не може бути

2020-12-04 10:46 UTC, Layrovell commented on src/index.html
> +                <strong class="wow animate__animated animate__fadeInUp"
> що означає клас wow ?

це wow.js хотфла його використати, щоби додати інтерактивності

2020-12-04 15:38 UTC, Denchepornyuk approved these changes

2024-05-21 11:25 UTC, closed without merging