Old-miami
mate-academy/layout_miami pull request #317
Opened 2021-01-28 18:16 UTC by Jastler

[DEMO LINK](https://jastler.github.io/layout_miami/)

2021-02-02 18:05 UTC, bogdandobak requested changes

2021-02-02 18:05 UTC, bogdandobak commented on src/styles/_header.scss
> +
```suggestion
 position: relative;

  height: 765px;

  font-weight: 500;
  line-height: 1;
  
  background-image: url("../images/header.jpg");
  background-size: cover;
  background-position: center;
```

2021-02-02 18:05 UTC, bogdandobak commented on src/styles/_header.scss
> +    color: white;
```suggestion
    position: absolute;
    top: 35px;
    left: calc(50% - #{$logo-width / 2});
    
    display: flex;
    
    color: white;
```

2021-02-02 18:05 UTC, bogdandobak commented on src/styles/_photos.scss
> +    img {
задавай класи , не використовуй теги

2021-02-02 18:05 UTC, bogdandobak commented on src/styles/_photos.scss
> +
тут також не використовуй теги

2021-02-02 18:07 UTC, misha-lysak requested changes

2021-02-02 18:07 UTC, misha-lysak commented on src/styles/_header.scss
> +    text-decoration: none;
колір краще задавати через # або rgb

2021-02-02 18:07 UTC, misha-lysak commented on src/styles/_header.scss
> +    text-decoration: none;
або ж винести у змінну

2021-02-02 18:07 UTC, misha-lysak commented on src/styles/_photos.scss
> +
```suggestion
      &__img {
  
```

2021-02-02 19:31 UTC, misha-lysak approved these changes

2021-02-02 19:38 UTC, bogdandobak approved these changes

2021-02-03 14:53 UTC, Vladimir-Beliy commented
очень большой скейл 
![image](https://user-images.githubusercontent.com/60401137/106764316-5aaa9180-6640-11eb-8bf8-0856b3fb72dc.png)

тут еще можно в две колонки 
![image](https://user-images.githubusercontent.com/60401137/106764348-6302cc80-6640-11eb-9e97-40836b638cad.png)

2021-02-03 14:56 UTC, Vladimir-Beliy requested changes
Хорошая работа, нужно немного подфиксить

2021-02-03 14:56 UTC, Vladimir-Beliy commented on src/index.html
> +          <a class="header__link link__phone" href="tel:+12345">
два элемента не должно быть

2021-02-03 14:56 UTC, Vladimir-Beliy commented on src/styles/_link.scss
> +}
Вложенность

2021-02-03 14:56 UTC, Vladimir-Beliy commented on src/styles/_nav.scss
> +  }
давай перенесем внутрь блока

2021-02-03 15:56 UTC, Vladimir-Beliy approved these changes

2026-05-12 17:03 UTC, closed without merging