Develop
mate-academy/layout_miami pull request #360
Opened 2021-02-17 15:24 UTC by JohnCrownHC

[DEMO LINK](https://JohnCrownHC.github.io/layout_miami/)

2021-02-18 10:57 UTC, danheim commented
Следует ограничит контент по ширине, не должен разъезжаться при больших разрешениях
https://prnt.sc/zyvkvr
Добавь курсор поинтер на кнопки

2021-02-18 11:00 UTC, danheim reviewed
не сокращай названия

2021-02-18 11:00 UTC, danheim commented on src/styles/header.scss
> +  @include BGImg;
не сокращай

2021-02-22 09:46 UTC, Denchepornyuk commented
https://www.notion.so/Bohdan-Prokopov-Miami-14d0d85abd624361afeb3f1822af2d24

2021-02-23 09:03 UTC, Denchepornyuk requested changes
https://www.notion.so/Bohdan-Prokopov-Miami-2-1ad5c9366c794ee3b939ba69a4d2ea53

2021-02-24 09:03 UTC, Denchepornyuk commented
Ширина екрана 865px з'являється біла полоска збоку екрана і текст в навігані переноситься `About us`, a текст не має переноситись на нову лінію. Біла полоска з'являється через блок Consultation
![image](https://user-images.githubusercontent.com/37452763/108976119-dfad2780-768f-11eb-8918-98199f3cd865.png)

2021-02-24 09:05 UTC, Denchepornyuk commented
моб меню має закривати повністю картинку miami
![image](https://user-images.githubusercontent.com/37452763/108976415-2864e080-7690-11eb-94e2-5d4df1172b59.png)

2021-02-24 09:05 UTC, Denchepornyuk approved these changes

2024-04-18 12:33 UTC, closed without merging