Develop
mate-academy/layout_miami pull request #462
Opened 2021-06-12 12:24 UTC by tolik-bilokrylov

https://tolik-bilokrylov.github.io/layout_miami/

2021-06-14 15:08 UTC, ArtemTopolskyi requested changes
https://www.loom.com/share/1558cf3d8d5b499db34ff7788d88ab04
Записал короткий видос по твоему лендингу

2021-06-14 17:03 UTC, ArtemTopolskyi requested changes
https://www.loom.com/share/5ecd385c84f74870a834c3767f13f938

2021-06-14 17:30 UTC, tolik-bilokrylov commented
> https://www.loom.com/share/5ecd385c84f74870a834c3767f13f938

https://www.loom.com/share/6be2331e40f34ec5bf951b4e236f3ed9
Был добавлен скайл, не знаю почему он не сработал...

2021-06-14 17:46 UTC, ArtemTopolskyi approved these changes

2021-06-16 10:06 UTC, ArtemTopolskyi requested changes
![image](https://user-images.githubusercontent.com/57574816/122199006-56219f80-cea2-11eb-80ea-9c58d962464c.png)
лого/навигация находятся не строго по центру

![image](https://user-images.githubusercontent.com/57574816/122199062-65085200-cea2-11eb-8e4b-66ca1f9692b6.png)
весь синий текст на странице - ссылки

![image](https://user-images.githubusercontent.com/57574816/122199178-7e110300-cea2-11eb-80d1-1814f6d2f5f2.png)
шрифт не соответствует дизайну

измени hover and focus эффекты формы, что бы они соответствовали фигме, убери ресайз с textarea http://htmlbook.ru/faq/kak-zapretit-izmenenie-razmerov
![image](https://user-images.githubusercontent.com/57574816/122199403-ad277480-cea2-11eb-8140-86ec01ad0a78.png)

2021-06-16 11:44 UTC, ArtemTopolskyi approved these changes

2025-03-11 13:49 UTC, closed without merging