1st commit Miami: header, menu, about, gallery
mate-academy/layout_miami pull request #467
Opened 2021-06-14 07:17 UTC by gponomarenko

https://gponomarenko.github.io/layout_miami/

2021-06-14 10:54 UTC, solaryasha approved these changes
Good job, 

1.  додай transition для всіх змін станів (hover i так далі)
2.  І додай [target blank](https://mateacademy.slack.com/archives/C021CDS2J79/p1623667549396700)

2021-06-15 14:21 UTC, solaryasha requested changes
Бракує відступів
<img width="1440" alt="Screenshot 2021-06-15 at 17 19 04" src="https://user-images.githubusercontent.com/32794096/122069526-ef4aaa80-cdfd-11eb-9dd8-809a13683ed1.png">

Текст має починатися з самого початку `textarea`
<img width="624" alt="Screenshot 2021-06-15 at 17 19 40" src="https://user-images.githubusercontent.com/32794096/122069578-f8d41280-cdfd-11eb-9fe4-5743b441baae.png">

У форми має бути метод POST

2021-06-15 15:57 UTC, gponomarenko commented
> Бракує відступів
> <img alt="Screenshot 2021-06-15 at 17 19 04" width="1440" src="https://user-images.githubusercontent.com/32794096/122069526-ef4aaa80-cdfd-11eb-9dd8-809a13683ed1.png">
> 
> Текст має починатися з самого початку `textarea`
> <img alt="Screenshot 2021-06-15 at 17 19 40" width="624" src="https://user-images.githubusercontent.com/32794096/122069578-f8d41280-cdfd-11eb-9fe4-5743b441baae.png">
> 
> У форми має бути метод POST

Додав! найскладніше виявилося прибрати пробіли всередині textarea, бо по HMTLLint інакше не проходила перевірка. Довелося додавати "милицю" через JS.

2021-06-16 06:25 UTC, solaryasha reviewed
Не все меню влазить на екран
<img width="747" alt="Screenshot 2021-06-16 at 09 24 58" src="https://user-images.githubusercontent.com/32794096/122168331-d20cef00-ce84-11eb-8bb2-b20a20bf56f6.png">

2021-06-16 06:34 UTC, solaryasha requested changes
Хороша робота, давай зробимо її ідеальною

2021-06-16 06:34 UTC, solaryasha commented on src/index.html
> +            >
```suggestion
            <img
              class="logo__image"
              src="images/logo.png" 
              alt="Miami Condo Kings logo"
            >
```

2021-06-16 06:34 UTC, solaryasha commented on src/index.html
> +                alt="Marina Palms view1" class="gallery__picture"
Неінформативний опис в `alt`, краще не використовуй цифри тут

2021-06-16 06:34 UTC, solaryasha commented on src/index.html
> +                  rel="noopener"
```suggestion
                  href="https://www.linkedin.com/in/lesliemckinneychicago"
                  class="testimonials__card-link"
                  target="_blank"
                  rel="noopener"
```

2021-06-16 06:34 UTC, solaryasha commented on src/scripts/main.js
> +// const message = form.elements
Не залишай коменти

2021-06-16 06:34 UTC, solaryasha commented on src/scripts/main.js
> +}
Зрозумів навіщо цей код, покажу на занятті, як можна обійтися без цього

2021-06-16 06:34 UTC, solaryasha commented on src/styles/blocks/_about-us.scss
> +    color: #000;
Кольори винось в змінні

2021-06-16 06:34 UTC, solaryasha commented on src/styles/blocks/_button.scss
> +  flex-direction: row;
Це дефолтне значення

2021-06-16 06:34 UTC, solaryasha commented on src/styles/blocks/_button.scss
> +      transition: color 0.3s ease-in-out;
Зазвичай transition відбуваютсья з таким самим часом, тому можеш його винести в змінну

2021-06-16 06:34 UTC, solaryasha commented on src/styles/blocks/_consult.scss
> +  display: block;
Форма ,по дефолту, блочний елемент

2021-06-16 06:34 UTC, solaryasha commented on src/styles/blocks/_consult.scss
> +      outline: none !important;
Чи потрібен тут `important` ?

2021-06-16 06:34 UTC, solaryasha commented on src/styles/blocks/_gallery.scss
> +    /* position: relative; */
Не залишай коменти

2021-06-16 06:34 UTC, solaryasha commented on src/styles/blocks/_nav.scss
> +  margin-bottom: 0;
У бем блока не може бути зовнішніх відступів

2021-06-16 09:53 UTC, gponomarenko commented on src/styles/blocks/_nav.scss
> +  margin-bottom: 0;
переробив через падінг

2021-06-16 09:53 UTC, gponomarenko commented on src/styles/blocks/_gallery.scss
> +    /* position: relative; */
прибрав

2021-06-16 09:54 UTC, gponomarenko commented on src/styles/blocks/_consult.scss
> +      outline: none !important;
скоріше, що ні. ))) прибрав

2021-06-16 09:54 UTC, gponomarenko commented on src/styles/blocks/_consult.scss
> +  display: block;
))) shame on me

2021-06-16 09:54 UTC, gponomarenko commented on src/styles/blocks/_button.scss
> +      transition: color 0.3s ease-in-out;
зробив

2021-06-16 09:58 UTC, gponomarenko commented
> Хороша робота, давай зробимо її ідеальною

Дякую дуже за підтримку та зауваження!

2021-06-16 10:10 UTC, gponomarenko commented on src/scripts/main.js
> +}
👍

2021-06-16 10:10 UTC, gponomarenko commented on src/styles/blocks/_button.scss
> +  flex-direction: row;
OK

2021-06-16 10:10 UTC, gponomarenko commented on src/styles/blocks/_about-us.scss
> +    color: #000;
всі кольори виніс

2021-06-16 10:10 UTC, gponomarenko commented on src/scripts/main.js
> +// const message = form.elements
ок

2021-06-16 10:11 UTC, gponomarenko commented on src/index.html
> +                  rel="noopener"
✅

2021-06-16 10:12 UTC, gponomarenko commented on src/index.html
> +                alt="Marina Palms view1" class="gallery__picture"
✅

2021-06-16 10:12 UTC, gponomarenko commented on src/index.html
> +            >
✅

2021-06-16 10:12 UTC, gponomarenko commented
> Не все меню влазить на екран
> <img alt="Screenshot 2021-06-16 at 09 24 58" width="747" src="https://user-images.githubusercontent.com/32794096/122168331-d20cef00-ce84-11eb-8bb2-b20a20bf56f6.png">

✅

2021-06-16 12:08 UTC, solaryasha approved these changes
Good job ! 🚀

2023-11-06 19:22 UTC, closed without merging