i did my first landing
mate-academy/layout_miami pull request #515
Opened 2021-07-22 12:56 UTC by RomSmile

DEMO LINK: https://RomSmile.github.io/layout_miami/

2021-07-22 17:17 UTC, Serhii-Usenko reviewed
excellent

2021-07-22 17:17 UTC, Serhii-Usenko commented on src/styles/blocks/header.scss
> +
its center but u have it https://prnt.sc/1eesm23

2021-07-22 17:17 UTC, Serhii-Usenko commented on src/styles/blocks/form-field.scss
> +}
U dont have "message" https://prnt.sc/1eet21c

2021-07-22 17:17 UTC, Serhii-Usenko commented on src/index.html
> +              / Miami Beach, FL 33139
no link

2021-07-23 11:32 UTC, danheim commented
https://www.loom.com/share/89999b713a864e56a572c8e1f7cf9f27
use google fonts to import Roboto

2021-07-26 06:52 UTC, Denchepornyuk requested changes
https://www.loom.com/share/b0337d39b4b8425d9cd0d58b2400e324

2021-07-27 14:52 UTC, Denchepornyuk approved these changes

2023-10-01 18:11 UTC, closed without merging