Miami 🏖
mate-academy/layout_miami pull request #593
Opened 2021-09-02 17:08 UTC by caelum29

[🏝 DEMO LINK ⛱](https://caelum29.github.io/layout_miami/)

2021-09-03 14:49 UTC, yungvitik commented on src/index.html
> +                  type="text"
```suggestion
                  type="email"
```

2021-09-03 15:12 UTC, yungvitik requested changes
Привіт) Є невеликі зауваження:
1) фоновий колір сторінки має бути білим
2) при наведенні посилання в секції "Contact us" мають змінювати колір.
3) при наведенні фото в "testimonials" мають змінювати розмір
4) в альбомному режимі на телефоні не видно всіх пунктів меню

2021-09-03 15:12 UTC, yungvitik commented on src/index.html
> +                <textarea name="message" placeholder="Message" class="form-field form-field--text contact-us__field--last"></textarea>
До поля message  можна додати атрибут мінімальної довжити щоб користувач не зміг відправити одну букву або слово.

2021-09-06 09:41 UTC, yungvitik approved these changes

2021-09-06 11:09 UTC, OleksiiBlezniuk requested changes
Хорошая работа но кое-что нужно исправить:

1) Ссылки которые ведут на сторонние ресурсы должны открываться в отдельной вкладке

2) Было бы неплохо добавить hover эффекты к ссылкам в галерее

3) Сейчас у тебя скроллится страница под менюшкой, поэтому, не зная что менюшка находится поверх экрана, можно проскроллить вниз, после чего переход по навигации будет дезориентирующим, советую при открытии менюшки отключать скролл страницы🙂

https://user-images.githubusercontent.com/84275496/132208013-efe6137d-6d56-4d6f-9374-8d4b88ae139a.mov

4) У тебя имена в карточках сделаны ссылками, но при этом эти ссылки ведут вверх страницы, что не очень логично, я как пользователь вижу под фотографией ссылку, думаю что там информация про этого человека, а ссылка перекидывает меня вверх и мне нужно скроллить вниз чтобы продолжить читать 🙂 Поэтому лучше или вставить ссылки на профили этих людей например, или убрать с имён ссылки

5) Ещё советую сделать адаптив под планшеты, так как сейчас у тебя при ширине экрана меньше 1024рх страница выглядит так:

<img width="1440" alt="Снимок экрана 2021-09-06 в 14 08 30" src="https://user-images.githubusercontent.com/84275496/132208322-1e1741d4-0d79-4b74-847d-fd93cef5abc2.png">
<img width="1440" alt="Снимок экрана 2021-09-06 в 14 08 40" src="https://user-images.githubusercontent.com/84275496/132208343-d226cbde-2004-4df5-a762-4a0c596d7738.png">

2021-09-14 13:02 UTC, Ihor-Karpyn requested changes
demo link н відкривається

2021-09-15 12:02 UTC, Anna-Tkachenko approved these changes
Еще несколько исправлений:
- При клике на логотип переходит на 404 error, тоже самое по ссылке Over 50 years experience in love. - fix it
- Ссылки в галерее на карты должны открываться в новой вкладке
- При переходе по какой-либо ссылке из меню пропадает возможность скроллить - исправь это

2025-10-31 11:25 UTC, closed without merging