Layout Miami
mate-academy/layout_miami pull request #605
Opened 2021-09-05 18:20 UTC by Mariia-Torkaienko

[DEMO LINK](https://Mariia-Torkaienko.github.io/layout_miami/)

2021-09-06 12:57 UTC, roman-toritsyn commented
Как всегда на высоте. Замечания только 2.
Добавть favicon.
Основной блок прилип к хедеру. Между ними должно быть расстояние.

2021-09-06 13:16 UTC, roman-toritsyn approved these changes

2021-09-06 14:16 UTC, OleksiiBlezniuk requested changes
Хорошая работа, но нужно кое-что исправить:

1. Слишком большой нижний отступ у заголовка в header. Нужно сбросить margin
2. Добавь hover эффекты на ссылки в gallery и contact us

Следующие замечания не обязательно исправлять, но рекомендуется:
1. Нужно отключить скролл страницы при открытой менюшке
2. Нужно сделать адаптив для планшетов

2021-09-07 12:50 UTC, OleksiiBlezniuk requested changes
У тебя сейчас выключен скролл по умолчанию, исправь пожалуйста. Нужно скинуть margin у заголовка в  header, потому что сейчас у тебя нижний отступ больше чем в дизайне. И scale - не самое лучшее решение для hover эффекта для ссылки, лучше используй смену цвета или подчёркивание🙂

2021-09-07 13:28 UTC, Mariia-Torkaienko commented
> У тебя сейчас выключен скролл по умолчанию, исправь пожалуйста. Нужно скинуть margin у заголовка в  header, потому что сейчас у тебя нижний отступ больше чем в дизайне. И scale - не самое лучшее решение для hover эффекта для ссылки, лучше используй смену цвета или подчёркивание🙂

я вже усе замінила. не розумію, чому тепер лінк підвисає.

2021-09-07 15:09 UTC, OleksiiBlezniuk approved these changes
 Good job! 🚀

2023-06-26 19:08 UTC, closed without merging