solution
mate-academy/layout_miami pull request #622
Opened 2021-09-07 09:06 UTC by YuliiaShyshka

2021-09-08 13:22 UTC, mykola-yarchuk requested changes
додай demo link щоб можна було поклікати і перевірити як виглядає

2021-09-09 07:46 UTC, YuliiaShyshka commented
> додай demo link щоб можна було поклікати і перевірити як виглядає

https://yuliiashyshka.github.io/layout_miami/

2021-09-09 08:27 UTC, mykola-yarchuk requested changes
![image](https://user-images.githubusercontent.com/35385361/132650733-0895c420-6f5d-4c57-9d71-5563ef696068.png)
номер не по центру, а в дизайні по центру

![image](https://user-images.githubusercontent.com/35385361/132650826-21f60ac4-aa76-4ccc-90e8-9545cde9d6a7.png)
лінка на testimonial не працює

![image](https://user-images.githubusercontent.com/35385361/132650890-56cd5c55-3e12-4955-ac5f-514dc5b20553.png)
плейсхолдера для textarea немає
і зроби поля форми обовязковими щоб не можна було відправити пусту форму

2021-10-07 12:38 UTC, closed without merging

2021-10-08 11:54 UTC, varseniuk requested changes

2021-10-08 11:54 UTC, varseniuk commented on src/index.html
> +                </textarea>
```suggestion
                  class="contact-us__field contact-us__field--last form-field form-field--textarea"
               ></textarea>
```
Плейсхолдера і досі немає. Це фікситься оттаким форматуванням (потрібно закриваючу дужку перемістити на ОДИН відступ вліво
Також, ми й досі можемо відправити пусту форму


https://user-images.githubusercontent.com/66570142/136552440-f774fff6-afe3-423b-ad80-3f66ddf59050.mov

2021-10-13 15:53 UTC, vkryvytskyy approved these changes