Myami layout by Sak Vladyslav
mate-academy/layout_miami pull request #627
Opened 2021-09-14 11:03 UTC by SakVladyslav

[DEMO LINK](https://sakvladyslav.github.io/layout_miami/)

2021-09-14 13:03 UTC, mykola-yarchuk requested changes
![image](https://user-images.githubusercontent.com/35385361/133261251-9cd9300d-0eb1-4574-a3ce-85bdc475795d.png)
тут телефон не по центру

2021-09-14 13:03 UTC, mykola-yarchuk commented on src/index.html
> +      <a href="/" class="logo">
```suggestion
      <a href="#" class="logo">
```

2021-09-14 13:03 UTC, mykola-yarchuk commented on src/index.html
> +      <a href="/" class="logo">
![image](https://user-images.githubusercontent.com/35385361/133262345-6ff60910-8645-4d12-b7c7-9ef0414871f1.png)
зараз веде на 404

2021-09-14 14:15 UTC, SakVladyslav commented on src/index.html
> +                </textarea>
Якщо роблю таке форматування, не проходить лінтер.
![Screenshot 2021-09-14 at 17 15 42](https://user-images.githubusercontent.com/55581154/133274380-f94e0a19-4eb8-4bf8-bde9-af4cc5c35b4a.png)
Хоча в мене ідентація 16

2021-09-16 08:15 UTC, mykola-yarchuk approved these changes

2024-03-03 15:34 UTC, closed without merging