miami landing demo
mate-academy/layout_miami pull request #748
Opened 2021-12-01 12:10 UTC by vladyslav-harkusha

https://vladyslav-harkusha.github.io/layout_miami/

2021-12-01 16:39 UTC, JHesher commented on src/index.html
> +            </a>
3. Logos in header and footer should be links to home page

2021-12-01 16:39 UTC, JHesher commented on src/index.html
> +            <a href="tel:+1 234 555-55-55" class="icon icon--phone header__call"></a>
you should use "tel" not "tell"

2021-12-01 16:39 UTC, JHesher commented on src/index.html
> +          </a>
"tell" - is wrong

2021-12-01 16:39 UTC, JHesher commented on src/index.html
> +      </a>
should be links to home page

2021-12-01 16:39 UTC, JHesher commented on src/styles/blocks/header.scss
> +
номер не відцентрований
![image](https://user-images.githubusercontent.com/82521260/144273613-027ae414-0e55-4ef6-b00c-fee1b3c6b91f.png)

2021-12-01 20:28 UTC, JHesher approved these changes

2021-12-02 08:43 UTC, ArtemTopolskyi requested changes
![image](https://user-images.githubusercontent.com/57574816/144386516-5c14fbeb-0817-4899-a338-9fb1aeedc43d.png)
анимации можно сделать менее агрессивными, чтобы картинки не налазили на соседние

страница не должна перезагружаться при отправке формы
https://developer.mozilla.org/ru/docs/Web/API/Event/preventDefault

Отличная работа :fire:

2021-12-02 08:43 UTC, ArtemTopolskyi commented on src/index.html
> +              <form action="">
```suggestion
              <form action="#">
```

2021-12-02 14:02 UTC, ArtemTopolskyi requested changes
Страница не должна обновляться при сабмите формы, https://developer.mozilla.org/ru/docs/Web/API/Event/preventDefault

2021-12-06 07:35 UTC, Denchepornyuk requested changes
https://bottlenose-barometer-ccb.notion.site/Miami-Harkusha-Vlad-c6625ecfaf2d4ae49e4e0d6de393446d

2021-12-06 12:01 UTC, Denchepornyuk approved these changes

2024-10-30 20:02 UTC, closed without merging