landing miami
mate-academy/layout_miami pull request #765
Opened 2021-12-02 15:06 UTC by mykola-koval

- [DEMO LINK](https://mykola-koval.github.io/layout_miami)

2021-12-02 15:12 UTC, AlonaSnigur approved these changes

2021-12-06 12:33 UTC, Denchepornyuk requested changes
![Screenshot 2021-12-06 at 14 33 08](https://user-images.githubusercontent.com/37452763/144846749-78edc1a0-c252-4636-b288-7cac623d3b79.png)
картинка не має налазити на іншу картинку під час hover

2021-12-06 12:34 UTC, Denchepornyuk commented
![Screenshot 2021-12-06 at 14 34 10](https://user-images.githubusercontent.com/37452763/144846857-19a8d529-c1ca-460e-a872-a82aad569a66.png)
адреса має відкриватись у новій вкладці

2021-12-07 10:46 UTC, Denchepornyuk approved these changes

2023-03-02 06:05 UTC, closed without merging