Miami landing
mate-academy/layout_miami pull request #771
Opened 2021-12-02 17:43 UTC by gnosis-frog

[DEMO LINK](https://gnosis-frog.github.io/layout_miami/)

2021-12-03 09:54 UTC, marina-tilniak reviewed
here і адреса в кінці повинні відкривати нову вкладку

більша картинка перекриває меншу, можливо варто трохи зменшити scale

посилання під картинками краще вставити на різні місця

У testimonials між посадою і описом трохи більший відступ у фігмі

якщо натиснути на лого в меню, то викидає 404(заодно і у себе помилку знайшла))

2021-12-03 10:54 UTC, marina-tilniak approved these changes

2021-12-06 15:36 UTC, Olexandr6 commented
Якщо інпути пусті і настискати на consultation то повинно висвітлюватись повідомлення під інпутами що їх потрібно заповнити, або ж використай HTML валідацію.

![image](https://user-images.githubusercontent.com/52370890/144874945-460fe97a-7e4d-42ab-bfc2-4818a9275985.png)

![image](https://user-images.githubusercontent.com/52370890/144875100-17e4586b-0edc-4856-9b21-3a46d85d92cc.png)

2021-12-06 15:41 UTC, Olexandr6 requested changes
Взагальному чудово зробив, проте глянь мої коменти 👆

2021-12-07 08:45 UTC, Denchepornyuk approved these changes

2023-02-08 11:02 UTC, closed without merging