Solution
mate-academy/layout_miami pull request #903
Opened 2022-02-16 17:27 UTC by Sachkovskyi

2022-02-17 09:13 UTC, varseniuk requested changes
Додай DEMO LINK, щоб можна було переглянути роботу

2022-02-17 11:17 UTC, Sachkovskyi commented
Не знаю, где найти его. В этом задании в файле README.MD есть ссылки только на фигму и чеклист.

2022-02-17 13:04 UTC, varseniuk requested changes
Demo link можна додати по аналогії з будь-яким іншим завданням:
https://<your_account>.github.io/layout_miami/

Текст не відцентрований відносно зображення
<img width="402" alt="Снимок экрана 2022-02-17 в 15 00 31" src="https://user-images.githubusercontent.com/66570142/154487226-48e71074-52db-4cb4-9478-eaef229e08ed.png">

Трішки зменш збільшення при хавері. Картинки залазять одна на одну
<img width="1212" alt="Снимок экрана 2022-02-17 в 15 00 45" src="https://user-images.githubusercontent.com/66570142/154487234-3ca2866d-b14b-4ac6-a375-bb661505bab7.png">

Добре було б, щоб це посилання відкривалось також у новому вікні
<img width="265" alt="Снимок экрана 2022-02-17 в 15 01 51" src="https://user-images.githubusercontent.com/66570142/154487252-3a9a928b-0b15-494c-93b7-950e84df5687.png">

2022-02-17 14:20 UTC, Sachkovskyi commented
https://Sachkovskyi.github.io/layout_miami/

2022-02-18 10:55 UTC, varseniuk approved these changes

2023-03-12 23:40 UTC, closed without merging