Create Miami page
mate-academy/layout_miami pull request #911
Opened 2022-03-01 19:18 UTC by ivan-kadykalo

[DEMO LINK](https://ivan-kadykalo.github.io/layout_miami/)

2022-03-10 11:45 UTC, Ihor-Karpyn requested changes
https://www.loom.com/share/92aac1c2d2134c7b8f55b697c739e04c

2022-03-14 16:58 UTC, AlinaMatuschak requested changes
Where did you get your design?
There another images:
https://www.figma.com/file/nHz8bflIwJaWP3P99vKTH5/miami_home_new?node-id=16033%3A3

Also you don't have home block, so better leave # on footer logo link

2022-03-15 07:19 UTC, ivan-kadykalo commented
> Where did you get your design? There another images: https://www.figma.com/file/nHz8bflIwJaWP3P99vKTH5/miami_home_new?node-id=16033%3A3
> 
> Also you don't have home block, so better leave # on footer logo link

All previous pictures are from forked repository.

2022-03-15 07:49 UTC, AlinaMatuschak approved these changes
Good work 💪

2022-03-15 07:49 UTC, AlinaMatuschak commented on src/index.html
> +                class="logo__image">
Don't forget about style code

```suggestion
              <img
                src="images/logo.png"
                alt="Miami Condo Kings logo"
                class="logo__image"
              >
```

2022-03-15 07:49 UTC, AlinaMatuschak commented on src/index.html
> +          </a>
Should fix that for all file

```suggestion
          <a
            href="tel:+1 234 555-55-55"
            class="menu__call menu__call--phone"
          >
            +1 234 555-55-55
          </a>
```

2022-03-15 07:49 UTC, AlinaMatuschak commented on src/index.html
> +              <p class="about__paragraph about__paragraph--important">We will never be late!<br>Guaranteed secure transaction - 100%</p>
long lines

2022-03-15 07:49 UTC, AlinaMatuschak commented on src/styles/blocks/footer.scss
> +  background-image: url(../images/newImg/img01.png);
```suggestion
  background: center / cover no-repeat url(../images/newImg/img01.png);
  height: 204px;
  padding-bottom: 24px;
```

2022-03-15 07:49 UTC, AlinaMatuschak commented on src/styles/blocks/header.scss
> +  background-image: url(../images/newImg/img02.png);
use background too

2022-03-15 07:49 UTC, AlinaMatuschak commented on src/styles/blocks/icon.scss
> +  // position: relative;
delete comment

2022-03-15 07:49 UTC, AlinaMatuschak commented on src/styles/blocks/page.scss
> +      background-repeat: no-repeat;
😉

2023-08-08 17:43 UTC, closed without merging