landing Miami created
mate-academy/layout_miami pull request #915
Opened 2022-03-08 12:15 UTC by maxxnikiforov

2022-03-09 08:41 UTC, VETALEK requested changes
All good, i think. Need just a few changes. And you should deploy your page on github pages, because i can't see it

2022-03-09 08:41 UTC, VETALEK commented on src/styles/blocks/_about.scss
> +    &-link {
```suggestion
    }
    
    &-link {
```
need empty line

2022-03-09 08:41 UTC, VETALEK commented on src/styles/blocks/_about.scss
> +  &__subtitle {
you skip empty lines in many places of code

2022-03-09 08:41 UTC, VETALEK commented on src/styles/blocks/_conteiner.scss
> +.conteiner {
```suggestion
.container {
```

2022-03-09 08:41 UTC, VETALEK commented on src/styles/blocks/_page.scss
> +      overflow: hidden;
i am not sure about that. Menu should be hidden even without this line

2022-03-09 08:41 UTC, VETALEK commented on src/styles/blocks/_place.scss
> +  &__photo-conteiner {
```suggestion
  &__photo-container {
```

2022-03-09 08:41 UTC, VETALEK commented on src/styles/blocks/_testimonials.scss
> +.testimonial {
this should be in a separate file

2022-03-09 08:41 UTC, VETALEK commented on src/styles/blocks/_testimonials.scss
> +.link {
and this

2022-03-10 08:32 UTC, maxxnikiforov commented on src/styles/blocks/_testimonials.scss
> +.link {
Согласен, сделаю.

2022-03-10 08:35 UTC, maxxnikiforov commented on src/styles/blocks/_about.scss
> +  &__subtitle {
Откорректирую. Спасибо за ревью!

2022-03-10 10:01 UTC, maxxnikiforov commented on src/styles/blocks/_conteiner.scss
> +.conteiner {
Орфографическую ошибку запомню, впредь не повторю!)

2022-03-10 10:05 UTC, maxxnikiforov commented on src/styles/blocks/_place.scss
> +  &__photo-conteiner {
Надеюсь на этот раз пропустят с грамматитеской ошибкой, чтоб не переписывать во всем проекте. Далее не допущу подобной ошибки.

2022-03-10 11:50 UTC, Ihor-Karpyn requested changes
https://www.loom.com/share/0bba6195b5ea4fec9eb55f63661a9a0a

2022-03-15 07:49 UTC, maxxnikiforov commented
> Where did you get your design? There are other images, you fixed just the image on the footer: https://www.figma.com/file/nHz8bflIwJaWP3P99vKTH5/miami_home_new?node-id=16033%3A3
> 
> also add smother scrolling, transition for phone hover on the header and on click here (Real estate (here)) open link on a new tap

По поводу скрола - он был установлен на body, переставил на всю страницу html. Замечания учел и исправил.

2022-03-15 10:44 UTC, AlinaMatuschak requested changes
Almost perfect:

- update this images (look design)
<img width="1028" alt="Screenshot 2022-03-15 at 12 39 50" src="https://user-images.githubusercontent.com/47606379/158360178-d3dc5ee0-c1f0-47a1-9aa8-35d53decb32d.png">
- add smoothly scroll to top on "view all" button
<img width="327" alt="Screenshot 2022-03-15 at 12 41 26" src="https://user-images.githubusercontent.com/47606379/158360435-a0ab0151-ea6c-4d5c-922b-090b6223dfaf.png">

2022-03-17 09:55 UTC, closed without merging

2022-03-17 10:32 UTC, AlinaMatuschak approved these changes

2022-03-17 10:32 UTC, AlinaMatuschak commented on src/styles/blocks/_button.scss
> +  transition: all 0.3s;
Always add a transition for styles that you want smoothly change
And create transition-duration variable

2022-03-17 10:32 UTC, AlinaMatuschak commented on src/index.html
> +          >+1 234 555-55-55</a>
```suggestion
          <a
            href="tel:+1 234 555-55-55"
            class="menu__call menu__call--phone"
          >
            +1 234 555-55-55
          </a>
```

2022-03-17 10:32 UTC, AlinaMatuschak commented on src/index.html
> +                      alt="Place 1"
Place 1 isn’t informative

2022-03-17 10:32 UTC, AlinaMatuschak commented on src/index.html
> +              </a>
```suggestion
               <a
                 href="https://goo.gl/maps/DCVawyM3qcksZgy8A"
                 class="place__link"
                 target="_blank"
               >
                Faena House <span class="place__link--grey"> / Miami Beach, FL 33140</span>
              </a>
```

2022-03-17 10:32 UTC, AlinaMatuschak commented on src/styles/blocks/_button.scss
> +    background-color: #005ecc;
create variable for color

2022-03-17 10:32 UTC, AlinaMatuschak commented on src/styles/blocks/_contact-us.scss
> +    &--last {
:last-child

2022-03-17 10:32 UTC, AlinaMatuschak commented on src/styles/blocks/_contact-us.scss
> +    &--last {
:last-child

2022-03-17 10:32 UTC, AlinaMatuschak commented on src/styles/blocks/_footer.scss
> +  background-size: cover;
```suggestion
  background: center / cover no-repeat url(../images/footer-L.png);
```

2022-03-17 10:32 UTC, AlinaMatuschak commented on src/styles/blocks/_header.scss
> +  background-repeat: no-repeat;
```suggestion
  background: center / cover no-repeat url(../images/header-L.png);
```

2022-03-17 10:32 UTC, AlinaMatuschak commented on src/styles/blocks/_place.scss
> +  &__photo-conteiner {
цей лендос піде на емплоймент, тому потрібно зробити максимально чисто )

2022-03-17 10:32 UTC, AlinaMatuschak commented on src/styles/blocks/_button.scss
> +    color: #fff;
$c-white

2022-03-17 10:32 UTC, AlinaMatuschak commented on src/styles/blocks/_button.scss
> +    color: #fff;
$c-white

2022-03-17 10:32 UTC, AlinaMatuschak commented on src/styles/blocks/_header.scss
> +        color: #fff;
$c-white

fix this everywhere